DROP TABLE IF EXISTS descriptor_index;
CREATE TABLE IF NOT EXISTS descriptor_index (
  uid       TEXT  NOT NULL,
  element   BYTEA NOT NULL,

  PRIMARY KEY (uid)
);

DROP TABLE IF EXISTS OBJECT_TRACK;
CREATE TABLE IF NOT EXISTS OBJECT_TRACK (
  TRACK_ID          INT               NOT NULL,
  FRAME_NUMBER      INT               NOT NULL,
  VIDEO_NAME        TEXT              NOT NULL,
  TIMESTAMP         BIGINT            NOT NULL,
  IMAGE_BBOX_TL_X   DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_TL_Y   DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_BR_X   DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_BR_Y   DOUBLE PRECISION  NOT NULL,
  TRACK_CONFIDENCE  DOUBLE PRECISION  NOT NULL
);

DROP INDEX IF EXISTS OBJECT_TRACK_ID_FRAME_VIDEO;
CREATE INDEX OBJECT_TRACK_ID_FRAME_VIDEO ON OBJECT_TRACK(
  TRACK_ID,
  FRAME_NUMBER,
  VIDEO_NAME
);

DROP TABLE IF EXISTS TRACK_DESCRIPTOR;
CREATE TABLE IF NOT EXISTS TRACK_DESCRIPTOR (
  UID         TEXT  NOT NULL,
  TYPE        TEXT  NOT NULL,
  VIDEO_NAME  TEXT  NOT NULL,

  PRIMARY KEY (UID)
);

DROP TABLE IF EXISTS TRACK_DESCRIPTOR_TRACK;
CREATE TABLE IF NOT EXISTS TRACK_DESCRIPTOR_TRACK (
  UID         TEXT  NOT NULL,
  TRACK_ID    INT   NOT NULL
);

DROP TABLE IF EXISTS TRACK_DESCRIPTOR_HISTORY;
CREATE TABLE IF NOT EXISTS TRACK_DESCRIPTOR_HISTORY (
  UID             TEXT              NOT NULL,
  FRAME_NUMBER    INT               NOT NULL,
  TIMESTAMP       BIGINT            NOT NULL,
  IMAGE_BBOX_TL_X DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_TL_Y DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_BR_X DOUBLE PRECISION  NOT NULL,
  IMAGE_BBOX_BR_Y DOUBLE PRECISION  NOT NULL,
  WORLD_BBOX_TL_X DOUBLE PRECISION,
  WORLD_BBOX_TL_Y DOUBLE PRECISION,
  WORLD_BBOX_BR_X DOUBLE PRECISION,
  WORLD_BBOX_BR_Y DOUBLE PRECISION
);
