# =============================================================================
# Title: Train Detector - LitDet (PyTorch Lightning Hydra)
#
# Description: Configuration for training SSDLite detector using LitDet.
# =============================================================================

include common_train_detector.conf

relativepath pipeline_template = templates/embedded_litdet.pipe

default_percent_validation = 0.10

detector_trainer:type = litdet

block detector_trainer:litdet
  train_directory = deep_training
  relativepath config_file = litdet/ssdlite.yaml
endblock
