#!/usr/bin/env bash

WS_DIR=${WS_DIR:-}
SRC_DIR=${SRC_DIR:-}
BUILD_DIR=${BUILD_DIR:-}
VIAME_REPO_DIR=${VIAME_REPO_DIR:-}

for VNAME in WS_DIR SRC_DIR BUILD_DIR VIAME_REPO_DIR
do
  if [[ -z "${!VNAME}" ]]
  then
    >&2 echo "\e[31m ERROR: Expected $VNAME environment variable that is missing. This must be set in dockerfile or put into environment \e[0m"
    exit 1
  else
    export "${VNAME}"
  fi
done

VIAME_BUILD_DIR=${BUILD_DIR}/viame
export VIAME_BUILD_DIR

cmake \
    -B ${VIAME_BUILD_DIR} \
    -S ${VIAME_REPO_DIR} \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DVIAME_BUILD_DEPENDENCIES:BOOL=ON \
    -DVIAME_BUILD_INTERNAL_PYTORCH:BOOL=OFF \
    -DVIAME_ENABLE_BURNOUT:BOOL=OFF \
    -DVIAME_DOWNLOAD_MODELS=OFF \
    -DVIAME_DOWNLOAD_MODELS-ARCTIC-SEAL:BOOL=OFF \
    -DVIAME_DOWNLOAD_MODELS-HABCAM:BOOL=OFF \
    -DVIAME_DOWNLOAD_MODELS-MOUSS:BOOL=OFF \
    -DVIAME_DOWNLOAD_MODELS-PYTORCH:BOOL=OFF \
    -DVIAME_ENABLE_CAFFE:BOOL=OFF \
    -DVIAME_ENABLE_CAMTRAWL:BOOL=OFF \
    -DVIAME_ENABLE_CUDA:BOOL=ON \
    -DVIAME_ENABLE_DOCS:BOOL=OFF \
    -DVIAME_ENABLE_FFMPEG:BOOL=OFF \
    -DVIAME_ENABLE_FASTER_RCNN:BOOL=OFF \
    -DVIAME_ENABLE_FLASK:BOOL=OFF \
    -DVIAME_ENABLE_ITK:BOOL=ON \
    -DVIAME_ENABLE_KWANT:BOOL=OFF \
    -DVIAME_ENABLE_MATLAB:BOOL=OFF \
    -DVIAME_ENABLE_OPENCV:BOOL=ON \
    -DVIAME_ENABLE_PYTHON:BOOL=ON \
    -DVIAME_ENABLE_PYTORCH:BOOL=OFF \
    -DVIAME_ENABLE_SCALLOP_TK:BOOL=OFF \
    -DVIAME_ENABLE_SEAL_TK:BOOL=OFF \
    -DVIAME_ENABLE_SMQTK:BOOL=OFF \
    -DVIAME_ENABLE_TENSORFLOW:BOOL=OFF \
    -DVIAME_ENABLE_UW_PREDICTOR:BOOL=OFF \
    -DVIAME_ENABLE_VIVIA:BOOL=OFF \
    -DVIAME_ENABLE_VXL:BOOL=ON \
    -DVIAME_ENABLE_YOLO:BOOL=ON\

cd ${VIAME_REPO_DIR}
VIAME_GIT_VERSION=$(git describe --always --tags --dirty)
export VIAME_GIT_VERSION

## Keep one processor free so system doesn't hang, which can happen with huge builds
NPROC_LESS_ONE="$((`nproc`<2?1:$((`nproc`-1))))"

cd ${VIAME_BUILD_DIR}
make -j${NPROC_LESS_ONE} fletch
make -j${NPROC_LESS_ONE} kwiver
make -j${NPROC_LESS_ONE}
