# This file is part of VIAME, and is distributed under an OSI-approved #
# BSD 3-Clause License. See either the root top-level LICENSE file or  #
# https://github.com/VIAME/VIAME/blob/main/LICENSE.txt for details.    #

from kwiver.vital.algo import MergeDetections

from kwiver.vital.types import BoundingBoxD
from kwiver.vital.types import DetectedObjectSet
from kwiver.vital.types import DetectedObject
from kwiver.vital.types import DetectedObjectType
from kwiver.vital.types import Image
from kwiver.vital.types import ImageContainer

import numpy as np

import ast

import contextlib, io
with contextlib.redirect_stdout(io.StringIO()):
    from map_boxes import *
from ensemble_boxes import *

try:
    from viame.core import detection_fusion_core as dfc
except ImportError:
    import detection_fusion_core as dfc

##############################################################################
# Inspired by https://github.com/ZFTurbo/Weighted-Boxes-Fusion
# Using metrics from https://github.com/ZFTurbo/Mean-Average-Precision-for-Boxes
# ProbEn fusion after Chen et al., "Multimodal Object Detection via
# Probabilistic Ensembling", ECCV 2022.
##############################################################################

bb_intersection_over_union = dfc.bb_intersection_over_union
find_matching_box = dfc.find_matching_box

def ensemble_box(boxes_list, scores_list, labels_list, weights, iou_thr,
                 skip_box_thr, sigma, fusion_type):

    assert len( boxes_list ) == len( weights )
    assert len( boxes_list ) == len( scores_list )
    assert len( boxes_list ) == len( labels_list )

    if fusion_type == 'nmw':
        boxes, scores, labels = non_maximum_weighted( boxes_list, scores_list, \
          labels_list, weights=weights, iou_thr=iou_thr, skip_box_thr=skip_box_thr )
    elif fusion_type == 'wbf':
        boxes, scores, labels = weighted_boxes_fusion( boxes_list, scores_list, \
          labels_list, weights=weights, iou_thr=iou_thr, skip_box_thr=skip_box_thr )
    elif fusion_type == 'soft_nms':
        boxes, scores, labels = soft_nms( boxes_list, scores_list, labels_list, \
          weights=weights, iou_thr=iou_thr, sigma=sigma, thresh=skip_box_thr )
    elif fusion_type == 'nms':
        boxes, scores, labels = nms( boxes_list, scores_list, labels_list, \
          weights=weights, iou_thr=iou_thr )
    else:
        raise ValueError( 'Unknown fusion type: ' + str( fusion_type ) )

    return boxes, scores, labels

class MergeDetectionsNMSFusion( MergeDetections ):
    """
    Implementation of MergeDetections class
    """
    def __init__( self ):
        MergeDetections.__init__( self )

        # Configuration settings for fusion
        self._fusion_type = 'nmw' # 'nmw', 'wbf', 'soft_nms', 'nms', 'proben'
        self._match_iou = 0.5
        self._iou_thr = 0.75
        self._skip_box_thr = 0.0001
        self._sigma = 0.1
        self._fusion_weights = [1, 1.5, 1]

        # Optional per-model score calibration, learned re-scoring of fused
        # outputs, and fusion of instance masks. The file inputs can be
        # generated by tools/train_detection_fusion.py.
        self._calibration_file = ''
        self._rescore_model_file = ''
        self._fuse_masks = False

        # These parameters should be deprecated longer-term
        self._height = 1
        self._width = 1

        # Complex parameters
        self._label_dic = {}
        self._pseudo_dic = {}
        self._pseudo_ind = {}
        self._id_dic = {}

        self._calibration = None
        self._rescore_model = None

    def get_configuration( self ):
        cfg = super( MergeDetections, self ).get_configuration()

        cfg.set_value( "fusion_type", self._fusion_type )
        cfg.set_value( "match_iou", str( self._match_iou ) )
        cfg.set_value( "iou_thr", str( self._iou_thr ) )
        cfg.set_value( "skip_box_thr", str( self._skip_box_thr ) )
        cfg.set_value( "sigma", str( self._sigma ) )
        cfg.set_value( "fusion_weights", str( self._fusion_weights ) )

        cfg.set_value( "calibration_file", self._calibration_file )
        cfg.set_value( "rescore_model_file", self._rescore_model_file )
        cfg.set_value( "fuse_masks", str( self._fuse_masks ) )

        cfg.set_value( "height", str( self._height ) )
        cfg.set_value( "width", str( self._width ) )

        cfg.set_value( "label_dic", str( self._label_dic ) )
        cfg.set_value( "pseudo_dic", str( self._pseudo_dic ) )
        cfg.set_value( "pseudo_ind", str( self._pseudo_ind ) )

        return cfg

    def set_configuration( self, cfg_in ):
        cfg = self.get_configuration()
        cfg.merge_config( cfg_in )

        self._fusion_type = str( cfg.get_value( "fusion_type" ) )
        self._match_iou = float( cfg.get_value( "match_iou" ) )
        self._iou_thr = float( cfg.get_value( "iou_thr" ) )
        self._skip_box_thr = float( cfg.get_value( "skip_box_thr" ) )
        self._sigma = float( cfg.get_value( "sigma" ) )
        self._fusion_weights = ast.literal_eval( cfg.get_value( "fusion_weights" ) )

        self._calibration_file = str( cfg.get_value( "calibration_file" ) )
        self._rescore_model_file = str( cfg.get_value( "rescore_model_file" ) )
        self._fuse_masks = str( cfg.get_value( "fuse_masks" ) ).lower() in \
          ( 'true', '1', 'yes', 'on' )

        self._height = float( cfg.get_value( "height" ) )
        self._width = float( cfg.get_value( "width" ) )

        self._label_dic = ast.literal_eval( cfg.get_value( "label_dic" ) )
        self._pseudo_dic = ast.literal_eval( cfg.get_value( "pseudo_dic" ) )
        self._pseudo_ind = ast.literal_eval( cfg.get_value( "pseudo_ind" ) )

        for label in self._label_dic:
            label_id = self._label_dic[ label ]
            if not label_id in self._id_dic:
                self._id_dic[ label_id ] = label

        if self._calibration_file:
            self._calibration = dfc.load_calibration( self._calibration_file )
        if self._rescore_model_file:
            self._rescore_model = dfc.load_rescore_model(
              self._rescore_model_file )

        return True

    def check_configuration( self, cfg ):
        return True

    def merge( self, det_sets ):

        n_models = len( det_sets )
        class_count = max( self._label_dic.values() ) + 1 \
                      if self._label_dic else 0

        weights = list( self._fusion_weights )
        if len( weights ) < n_models:
            weights = weights + [ 1.0 ] * ( n_models - len( weights ) )

        # Get detection HL info in a few lists
        boxes_list = []
        scores_list = []
        labels_list = []
        dists_list = []
        masks_list = []

        for model_ind, det_set in enumerate( det_sets ):
            box_list = []
            score_list = []
            label_list = []
            dist_list = []
            mask_list = []

            norm_width = self._width
            norm_height = self._height

            model_cal = None
            if self._calibration and model_ind < len( self._calibration ):
                model_cal = self._calibration[ model_ind ]

            for det in det_set:
                if det.type is None:
                    continue

                # Collect (optionally calibrated) scores for mapped classes
                class_scores = {}
                for class_name in det.type.class_names():
                    if not class_name in self._label_dic:
                        continue
                    class_score = det.type.score( class_name )
                    if model_cal is not None:
                        class_score = dfc.calibrate_model_score(
                          model_cal, class_name, class_score )
                    class_scores[ self._label_dic[ class_name ] ] = class_score

                if not class_scores:
                    continue

                top_label = max( class_scores, key=class_scores.get )
                bbox = det.bounding_box

                box_list.append( [
                  float( bbox.min_x() ) / norm_width,
                  float( bbox.min_y() ) / norm_height,
                  float( bbox.max_x() ) / norm_width,
                  float( bbox.max_y() ) / norm_height ] )
                score_list.append( class_scores[ top_label ] )
                label_list.append( top_label )
                dist_list.append( class_scores )

                if self._fuse_masks and det.mask is not None:
                    mask_list.append(
                      np.squeeze( np.asarray( det.mask.image() ) ) )
                else:
                    mask_list.append( None )

            boxes_list.append( box_list )
            scores_list.append( score_list )
            labels_list.append( label_list )
            dists_list.append( dist_list )
            masks_list.append( mask_list )

        all_boxes = [ box for box_list in boxes_list for box in box_list ]

        if self._width == 1 and len( all_boxes ) > 0:
            norm_width = max( [ x[2] for x in all_boxes ] ) + 1
            for box_list in boxes_list:
                box_list[:] = [ [ x[0] / norm_width, x[1],
                                  x[2] / norm_width, x[3] ]
                                for x in box_list ]
        if self._height == 1 and len( all_boxes ) > 0:
            norm_height = max( [ x[3] for x in all_boxes ] ) + 1
            for box_list in boxes_list:
                box_list[:] = [ [ x[0], x[1] / norm_height,
                                  x[2], x[3] / norm_height ]
                                for x in box_list ]

        # Utilize pseudonym lists when upsampling categories
        for chk_list_ind in self._pseudo_ind:
            for chk_ind in range( len( boxes_list[ chk_list_ind ] ) ):
                orig_label = labels_list[ chk_list_ind ][ chk_ind ]
                if not orig_label in self._pseudo_dic:
                    continue
                for other_list_ind in self._pseudo_ind[ chk_list_ind ]:
                    best_idx, best_iou = find_matching_box(
                        boxes_list[ other_list_ind ],
                        boxes_list[ chk_list_ind ][ chk_ind ],
                        self._match_iou )
                    if best_idx >= 0:
                        new_label = labels_list[ other_list_ind ][ best_idx ]
                        if new_label in self._pseudo_dic[ orig_label ]:
                            labels_list[ chk_list_ind ][ chk_ind ] = new_label
                            break

        # Run merging algorithm
        need_contribs = self._rescore_model is not None or self._fuse_masks
        contributors = None
        fused_dists = None

        if self._fusion_type == 'proben':
            np_boxes = [ np.array( b, dtype=float ).reshape( -1, 4 )
                         for b in boxes_list ]
            dist_arrays = [ dfc.dists_to_array( d, class_count )
                            for d in dists_list ]
            out_boxes, out_scores, out_labels, fused_dists, contributors = \
              dfc.proben_fusion( np_boxes, scores_list, labels_list,
                dist_arrays, weights, self._iou_thr, self._skip_box_thr )
        else:
            out_boxes, out_scores, out_labels = ensemble_box(
              boxes_list, scores_list, labels_list,
              weights, self._iou_thr,
              self._skip_box_thr, self._sigma, self._fusion_type )
            if need_contribs:
                contributors = dfc.find_contributors( out_boxes, out_labels,
                  boxes_list, labels_list, self._iou_thr )

        # Optional learned re-scoring using fusion agreement features
        out_scores = np.array( out_scores, dtype=float )
        if self._rescore_model is not None and contributors is not None:
            for i in range( len( out_scores ) ):
                features = dfc.compute_stack_features( out_scores[i],
                  contributors[i], scores_list, n_models )
                out_scores[i] = dfc.logistic_predict(
                  features, self._rescore_model )

        # Compile output detections
        output = DetectedObjectSet()

        for i in range( len( out_boxes ) ):
            score = float( out_scores[i] )
            box = out_boxes[i]
            label_id = int( out_labels[i] )
            bbox = BoundingBoxD(
              box[0] * norm_width,
              box[1] * norm_height,
              box[2] * norm_width,
              box[3] * norm_height )

            if fused_dists is not None:
                dot = DetectedObjectType()
                for class_id in range( class_count ):
                    if class_id == dfc.BACKGROUND_ID or \
                       not class_id in self._id_dic:
                        continue
                    class_score = float( fused_dists[i][ class_id ] )
                    if class_id == label_id and self._rescore_model is not None:
                        class_score = score
                    if class_score > 1e-4:
                        dot.set_score( self._id_dic[ class_id ], class_score )
                if not dot.class_names():
                    dot.set_score( self._id_dic[ label_id ], score )
            else:
                dot = DetectedObjectType( self._id_dic[ label_id ], score )

            det = DetectedObject( bbox, score, dot )

            if self._fuse_masks and contributors is not None:
                contrib_boxes = []
                contrib_masks = []
                contrib_weights = []
                for m, j, _ in contributors[i]:
                    if masks_list[m][j] is None:
                        continue
                    src = boxes_list[m][j]
                    contrib_boxes.append( [ src[0] * norm_width,
                                            src[1] * norm_height,
                                            src[2] * norm_width,
                                            src[3] * norm_height ] )
                    contrib_masks.append( masks_list[m][j] )
                    contrib_weights.append( weights[m] * scores_list[m][j] )
                fused_mask = dfc.fuse_mask_arrays(
                  [ box[0] * norm_width, box[1] * norm_height,
                    box[2] * norm_width, box[3] * norm_height ],
                  contrib_boxes, contrib_masks, contrib_weights )
                if fused_mask is not None:
                    det.mask = ImageContainer( Image( fused_mask ) )

            output.add( det )

        return output

def __vital_algorithm_register__():
    from kwiver.vital.algo import algorithm_factory

    # Register Algorithm
    implementation_name  = "nms_fusion"

    if algorithm_factory.has_algorithm_impl_name(
      MergeDetectionsNMSFusion.static_type_name(), implementation_name ):
        return

    algorithm_factory.add_algorithm( implementation_name,
      "Fusion of multiple different detections", MergeDetectionsNMSFusion )

    algorithm_factory.mark_algorithm_as_loaded( implementation_name )
