#!/usr/bin/env python3
"""Emit a wheel contents fragment for the pipelines that need no model.

Run by the `wheel` target before `build_wheel.py`, whose `--contents` takes
more than one file so a generated selection can be layered over the
hand-written list.

**Nothing from `configs/add-ons/` is ever selected.** Add-on packs are model
distributions -- `DEFAULT-FISH`, `GFIT`, `SAM3` and the rest, 8.6 GB of
weights across the ones this install carries -- and they are fetched at
runtime, not shipped. This script only ever looks at `configs/pipelines`,
and the exclusion is asserted rather than assumed: see `_refuse_add_ons`.

**What "needs no model" means.** A pipeline is selected when neither it nor
anything it `include`s, transitively, names a file under `models/`. That
catches the reference however it is spelled -- `relativepath weight =`,
`relativepath deployed =`, a bare `= models/x.pth` -- and the result was
checked against a second, looser pattern (any `.pth`, `.pt`, `.zip`,
`.onnx`, `.weights`, `.safetensors`, `.engine`, `.cfg`) which found no
pipeline the first had called model-free. Of 155 runnable pipelines, 82 are.

The point is a wheel whose pipelines all run on what it ships. A pipeline
whose `relativepath weight = models/gfit_groups_rf_detr_1728.pth` points at
nothing would be worse than absent: it looks installed and fails at
configure time.

`common_*.pipe` are includes rather than entry points, and are carried when
something selected includes them -- the closure is what is emitted, not the
82 alone.
"""

import argparse
import re
import sys
from pathlib import Path


INCLUDE = re.compile(r"^\s*include\s+(\S+)", re.M)

# A model reference, however the config spells it.
MODEL = re.compile(r"(?:relativepath\s+\w+\s*=\s*|:\S*model\S*\s+|=\s*)(models/\S+)")

# Looser: anything that looks like weights at all. Used to check the above,
# not to select.
WEIGHTS = re.compile(
    r"\.(?:pth|pt|zip|onnx|weights|caffemodel|safetensors|engine|cfg)\b"
    r"|relativepath\s+(?:deployed|weight|net_config|model)", re.I)


def _refuse_add_ons(path):
    """Add-on content must never reach the wheel."""
    if "add-ons" in path.parts or "add_ons" in path.parts:
        raise SystemExit(
            f"select_default_configs: refusing {path} -- it is add-on "
            f"content, which is fetched at runtime and never shipped")


def closure(entry, root, seen=None):
    """`entry` and everything it includes, transitively."""
    seen = seen if seen is not None else set()
    if entry in seen or not entry.is_file():
        return seen
    _refuse_add_ons(entry)
    seen.add(entry)
    for name in INCLUDE.findall(entry.read_text(errors="replace")):
        closure(root / name, root, seen)
    return seen


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--prefix", required=True, help="the install prefix")
    p.add_argument("--output", required=True, help="the contents fragment to write")
    p.add_argument("--destination", default="viame/configs/pipelines/",
                   help="where the configs land inside the wheel")
    args = p.parse_args(argv)

    root = Path(args.prefix) / "configs" / "pipelines"
    if not root.is_dir():
        raise SystemExit(f"select_default_configs: {root} is not a directory")

    selected, needs_model, mismatched = set(), 0, []
    for entry in sorted(root.glob("*.pipe")):
        if entry.name.startswith("common_"):
            continue                      # an include, carried by its users
        chain = closure(entry, root)
        text = "".join(c.read_text(errors="replace") for c in chain)
        if MODEL.search(text):
            needs_model += 1
            continue
        if WEIGHTS.search(text):
            # The loose pattern disagreeing with the strict one means a model
            # is referenced in a spelling `MODEL` does not know. Report it
            # rather than ship a pipeline that cannot run.
            mismatched.append(entry.name)
            continue
        selected |= chain

    if mismatched:
        print(f"  note: {len(mismatched)} pipeline(s) name no `models/` path but "
              f"do mention weights; left out: {mismatched[:4]}", file=sys.stderr)

    if not selected:
        raise SystemExit("select_default_configs: selected nothing")

    lines = [
        "# GENERATED by select_default_configs.py -- do not edit.",
        "#",
        "# The pipelines that need no model, and the `common_*.pipe` they",
        "# include. Nothing here comes from `configs/add-ons/`: add-on packs",
        "# are model distributions, fetched at runtime and never shipped.",
        "",
    ]
    for path in sorted(selected):
        rel = path.relative_to(Path(args.prefix)).as_posix()
        lines.append(f"include {rel} -> {args.destination}{path.name}")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    if not out.is_file() or out.read_text() != text:
        out.write_text(text)

    size = sum(p.stat().st_size for p in selected)
    print(f"  default configs: {len(selected)} files, {size / 1024:.0f} KB "
          f"({needs_model} pipelines left out as needing models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
