"""Old `kwiver.*` module names -> where P11-T02 put each one.

Reads the table out of `rename_python_modules.py` rather than repeating it,
so the shim and the rename cannot disagree about where a module went.

Writes `library/compat/python/kwiver/aliases.py`. Rerun it if the rename
table ever changes.
"""

import importlib.util
import os
import sys

HERE = os.path.dirname( os.path.abspath( __file__ ) )
OUT = os.path.join( HERE, os.pardir, os.pardir,
                    "library", "compat", "kwiver", "aliases.py" )

# Entry point *groups* are module-shaped but are not modules, so they are not
# import aliases. `discovery.py` reads the old group name directly instead.
NOT_MODULES = (
    "kwiver.python_plugin_registration",
    "kwiver.cpp_search_paths",
    "kwiver.python_plugins",
)


def main():
    spec = importlib.util.spec_from_file_location(
        "rp", os.path.join( HERE, "rename_python_modules.py" ) )
    rp = importlib.util.module_from_spec( spec )
    spec.loader.exec_module( rp )

    table = [ ( old, new ) for old, new in rp.MODULES
              if old not in NOT_MODULES ]
    table.sort()

    with open( OUT, "w", encoding = "utf-8" ) as out:
        out.write(
            "# Generated by design/scripts/build_kwiver_aliases.py from the\n"
            "# table in design/scripts/rename_python_modules.py.\n"
            "# Do not edit by hand.\n"
            "\n"
            "ALIASES = {\n" )
        for old, new in table:
            out.write( "    {!r}: {!r},\n".format( old, new ) )
        out.write( "}\n" )

    print( "wrote {} entries to {}".format(
        len( table ), os.path.normpath( OUT ) ) )
    return 0


if __name__ == "__main__":
    sys.exit( main() )
