"""Old `viame.<plugin>` module names -> where the file map put each module.

Reads design/lite-file-map.tsv. For every python file moved out of
plugins/{core,pytorch,opencv,onnx,colmap}, the old installed module name
is the plugin package plus its path, except the onnx exporters, which
installed flat as `viame.pytorch.<exporter>`. The new name is the library
path. A vendored tree that moved whole is aliased once, at its package.

Prints the tables; `--write DIR` writes one `aliases.py` per old package --
library/utilities/compat is where they live. Rerun it whenever the file map
changes a python destination.
"""

import collections
import os
import sys

PACKAGES = ("core", "pytorch", "opencv", "onnx", "colmap")

# Modules the file map cannot name, because it maps their C++ or binding
# sources rather than a `.py`. `viame.opencv.stereo_demo` and `stereo_expt`
# are absent on purpose: they were deleted (lite-library-layout.md section 4),
# and an old name that imports nothing should say so.
EXTRAS = {
    "core": {"viame.core._measurement": "viame.measurement._measurement"},
}


def module(path):
    return path[:-len(".py")].replace("/", ".")


def old_name(source):
    rel = source[len("plugins/"):]
    plugin, _, inner = rel.partition("/")
    if plugin == "pytorch" and inner.startswith("onnx_exporters/"):
        inner = inner.split("/", 1)[1]
    name = "viame." + plugin + "." + module(inner)
    return name[:-len(".__init__")] if name.endswith(".__init__") else name


def new_name(destination):
    name = "viame." + module(destination[len("library/"):])
    return name[:-len(".__init__")] if name.endswith(".__init__") else name


def main():
    rows = [l.rstrip("\n").split("\t") for l in open("design/lite-file-map.tsv") if "\t" in l]
    tables = collections.defaultdict(dict)
    unresolved = []
    for source, destination in rows:
        if not source.endswith(".py") or not source.startswith("plugins/"):
            continue
        plugin = source.split("/")[1]
        if plugin not in PACKAGES:
            continue
        if not destination.startswith("library/"):
            unresolved.append((source, destination))
            continue
        old, new = old_name(source), new_name(destination)
        if old == "viame." + plugin:
            continue  # the package itself stays, as the compatibility package
        tables[plugin][old] = new

    for plugin, extra in EXTRAS.items():
        tables[plugin].update(extra)

    # collapse a vendored tree that moved whole into one package alias
    for plugin, table in tables.items():
        by_parent = collections.defaultdict(list)
        for old, new in table.items():
            by_parent[old.rpartition(".")[0]].append((old, new))
        for parent in sorted(by_parent, key=len):
            if parent in table or parent == "viame." + plugin:
                continue
            children = [(o, n) for o, n in table.items() if o.startswith(parent + ".")]
            prefixes = {n[:len(n) - len(o) + len(parent)] for o, n in children
                        if n.endswith(o[len(parent):])}
            if len(prefixes) == 1 and all(n.endswith(o[len(parent):]) for o, n in children):
                target = prefixes.pop()
                for o, _ in children:
                    del table[o]
                table[parent] = target

    # drop every alias an aliased ancestor already implies: the finder
    # resolves the longest match, and `viame.pytorch.netharn` -> `...netharn`
    # covers `viame.pytorch.netharn.api` -> `...netharn.api` without a line
    for plugin, table in tables.items():
        for old in sorted(table, key=len, reverse=True):
            name = old.rpartition(".")[0]
            while name and name != "viame." + plugin:
                if name in table:
                    if table[old] == table[name] + old[len(name):]:
                        del table[old]
                    break
                name = name.rpartition(".")[0]

    for plugin in PACKAGES:
        table = tables.get(plugin, {})
        print("viame.%s: %d aliases" % (plugin, len(table)))
        for old in sorted(table)[:12]:
            print("   %-55s -> %s" % (old, table[old]))
        if len(table) > 12:
            print("   ...")
    print("rows with no library destination:", len(unresolved))
    for s, d in unresolved[:20]:
        print("   %s -> %s" % (s, d))

    if "--write" in sys.argv:
        out = sys.argv[sys.argv.index("--write") + 1]
        for plugin, table in tables.items():
            os.makedirs(os.path.join(out, plugin), exist_ok=True)
            with open(os.path.join(out, plugin, "aliases.py"), "w") as h:
                h.write("# Generated by design/scripts/build_compat_aliases.py from\n"
                        "# design/lite-file-map.tsv. Do not edit by hand.\n\n"
                        "ALIASES = {\n")
                for old in sorted(table):
                    h.write("    %r: %r,\n" % (old, table[old]))
                h.write("}\n")


if __name__ == "__main__":
    main()
