#!/usr/bin/env python3
"""design/lite-opencv-uses.txt -- what each OpenCV-using file asks OpenCV for.

Writes the per-file half of the inventory. The two name tables that follow it
in that file come from `ocv_backed.py` and `ocv_procs.py`; see their
docstrings. Run from the repository root.
"""
import re, subprocess, collections

AREAS = [
 ("2.1 bridge", [r'\bcv::Mat\b', r'\bcv::UMat\b', r'image_container', r'mat_image_memory',
                 r'\bcv::Rect\b', r'\bcv::Point\b', r'\bcv::Size\b', r'\bcv::Scalar\b']),
 ("2.2 codecs", [r'\bcv::imread\b', r'\bcv::imwrite\b', r'\bcv::imdecode\b', r'\bcv::imencode\b',
                 r'opencv2/imgcodecs', r'\bcv::VideoCapture\b', r'\bcv::VideoWriter\b']),
 ("2.3 imgproc", [r'\bcv::cvtColor\b', r'\bcv::resize\b', r'\bcv::warpAffine\b',
                  r'\bcv::warpPerspective\b', r'\bcv::remap\b', r'\bcv::filter2D\b',
                  r'\bcv::Sobel\b', r'\bcv::GaussianBlur\b', r'\bcv::blur\b', r'\bcv::medianBlur\b',
                  r'\bcv::erode\b', r'\bcv::dilate\b', r'\bcv::morphologyEx\b',
                  r'\bcv::getStructuringElement\b', r'\bcv::threshold\b', r'\bcv::adaptiveThreshold\b',
                  r'\bcv::connectedComponents', r'\bcv::findContours\b', r'\bcv::contourArea\b',
                  r'\bcv::convexHull\b', r'\bcv::minAreaRect\b', r'\bcv::boundingRect\b',
                  r'\bcv::calcHist\b', r'\bcv::normalize\b', r'\bcv::minMaxLoc\b',
                  r'\bcv::createCLAHE\b', r'\bcv::equalizeHist\b', r'\bcv::split\b', r'\bcv::merge\b',
                  r'\bcv::hconcat\b', r'\bcv::vconcat\b', r'\bcv::matchTemplate\b',
                  r'\bcv::Canny\b', r'\bcv::HoughCircles\b', r'\bcv::watershed\b',
                  r'\bcv::grabCut\b', r'\bcv::distanceTransform\b', r'\bcv::getRotationMatrix2D\b',
                  r'\bcv::copyMakeBorder\b', r'\bcv::pyrDown\b', r'\bcv::pyrUp\b']),
 ("2.4 calib3d", [r'\bcv::calibrateCamera\b', r'\bcv::stereoCalibrate\b', r'\bcv::stereoRectify\b',
                  r'\bcv::initUndistortRectifyMap\b', r'\bcv::undistort', r'\bcv::findChessboardCorners\b',
                  r'\bcv::cornerSubPix\b', r'\bcv::drawChessboardCorners\b', r'\bcv::solvePnP',
                  r'\bcv::Rodrigues\b', r'\bcv::findHomography\b', r'\bcv::findFundamentalMat\b',
                  r'\bcv::findEssentialMat\b', r'\bcv::triangulatePoints\b', r'\bcv::projectPoints\b',
                  r'\bcv::reprojectImageTo3D\b', r'StereoSGBM', r'StereoBM', r'opencv2/calib3d']),
 ("2.5 FileStorage", [r'\bcv::FileStorage\b', r'\bcv::FileNode']),
 ("2.6 ml/features/seg", [r'opencv2/ml', r'opencv2/features2d', r'opencv2/xfeatures2d',
                          r'\bcv::ml::', r'\bcv::SIFT\b', r'\bcv::ORB\b', r'\bcv::BFMatcher\b',
                          r'\bcv::FlannBasedMatcher\b', r'\bcv::KeyPoint\b', r'\bcv::DMatch\b',
                          r'\bcv::AKAZE\b', r'\bcv::BRISK\b', r'Feature2D', r'DescriptorMatcher',
                          r'\bcv::CascadeClassifier\b', r'opencv2/objdetect', r'\bcv::HOGDescriptor\b',
                          r'\bcv::getGaborKernel\b', r'\bcv::kmeans\b']),
 ("drawing", [r'\bcv::rectangle\b', r'\bcv::line\b', r'\bcv::circle\b', r'\bcv::putText\b',
              r'\bcv::fillPoly\b', r'\bcv::polylines\b', r'\bcv::drawMarker\b',
              r'\bcv::ellipse\b', r'\bcv::getTextSize\b', r'\bcv::drawContours\b']),
]


# Names that are the bridge, not an operation: every file that touches a
# cv::Mat has them and listing them per file says nothing.
BRIDGE = {
 'Mat', 'Mat_', 'UMat', 'Rect', 'Rect2d', 'Rect2f', 'Rect2i', 'Point', 'Point2f',
 'Point2d', 'Point2i', 'Point3f', 'Point3d', 'Size', 'Size2f', 'Scalar', 'Vec2f',
 'Vec3b', 'Vec3f', 'Vec3d', 'Vec4f', 'Vec4i', 'InputArray', 'OutputArray',
 'MatIterator_', 'Range', 'noArray', 'Ptr', 'String', 'RotatedRect', 'Point_',
 'saturate_cast', 'DataType', 'Exception', 'error', 'MatSize', 'MatStep',
}

files = subprocess.check_output(
    ["git", "grep", "-ln", "opencv2/", "--", "library", "tools", "plugins", "python"],
    text=True).split()

sym_re = re.compile(r'\bcv::([A-Za-z_][A-Za-z0-9_]*)')
inc_re = re.compile(r'#\s*include\s*<(opencv2/[^>]+)>')

rows = []
area_count = collections.Counter()
sym_count = collections.Counter()
for f in sorted(files):
    text = open(f, errors="replace").read()
    areas = []
    for name, pats in AREAS:
        if any(re.search(p, text) for p in pats):
            areas.append(name)
    areas = areas or ["2.1 bridge"]
    for a in areas:
        area_count[a] += 1
    syms = sorted({ s for s in sym_re.findall(text) if s not in BRIDGE })
    for s in syms:
        sym_count[s] += 1
    rows.append((f, areas, sorted(set(inc_re.findall(text))), syms))

out = []
w = out.append
w("# What each file asks OpenCV for (P7-T01)")
w("")
w("Generated by the inventory pass of P7-T01, from `git grep -ln \"opencv2/\"`")
w("over `library/`, `tools/`, `plugins/` and `python/`. The areas are")
w("`lite-removals.md` section 2's. `plugins/` is in scope even though the plan's")
w("task text names only `library/` and `tools/`: phase 2 has not moved those")
w("directories yet, so most of what phase 7 describes still lives there.")
w("")
w("`plugins/pytorch/learn` is excluded -- the python packages vendored there")
w("carry their own OpenCV and become wheels in phase 9.")
w("")
w("## Files per area")
w("")
w("| Area | Files |")
w("|---|---:|")
for name, _ in AREAS:
    w("| %s | %d |" % (name, area_count[name]))
w("")
w("A file counts once per area it touches, so the column sums past %d." % len(rows))
w("")
w("## The API surface, by how many files want it")
w("")
w("Class and free-function names under `cv::`, with the bridge types")
w("(`Mat`, `Rect`, `Point`, `Size`, `Scalar`, `Vec*`, `Ptr`, ...) left out:")
w("those are section 2.1 and every file has them.")
w("")
w("| Name | Files |")
w("|---|---:|")
for s, n in sym_count.most_common():
    w("| `cv::%s` | %d |" % (s, n))
w("")
w("## Per file")
w("")
for f, areas, incs, syms in rows:
    w("### `%s`" % f)
    w("")
    w("Areas: %s" % ", ".join(areas))
    w("")
    w("Includes: %s" % ", ".join("`%s`" % i for i in incs) if incs else "Includes: (transitive)")
    w("")
    if syms:
        w("Uses: %s" % ", ".join("`cv::%s`" % s for s in syms))
    else:
        w("Uses: bridge types only")
    w("")
print("\n".join(out))
