# VIAME Windows GPU Build Platform Configuration
#
# Uses shared cmake preset files for common settings

# CTest configuration
set(CTEST_SITE "noctae.kitware.com")
set(CTEST_BUILD_NAME "Windows_GPU_Main")
set(CTEST_SOURCE_DIRECTORY "C:/VIAME-Builds/GPU")
set(CTEST_BINARY_DIRECTORY "C:/VIAME-Builds/GPU/build/")
set(CTEST_CMAKE_GENERATOR "Visual Studio 18 2026")
set(CTEST_CMAKE_GENERATOR_INSTANCE "C:/Program Files/Microsoft Visual Studio/18/Community")
set(CTEST_BUILD_CONFIGURATION Release)
set(CTEST_PROJECT_NAME VIAME)
set(CTEST_BUILD_MODEL "Nightly")
set(CTEST_NIGHTLY_START_TIME "3:00:00 UTC")
set(CTEST_USE_LAUNCHERS 1)
include(CTestUseLaunchers)

# Include helper for building OPTIONS from cmake presets
include(${CMAKE_CURRENT_LIST_DIR}/build_common_functions.cmake)

# Include base cmake preset files
include_cmake_preset(build_cmake_base.cmake)
include_cmake_preset(build_cmake_desktop.cmake)

# Windows-specific CUDA paths
add_option("CUDA_NVCC_EXECUTABLE:PATH" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/bin/nvcc.exe")
add_option("CUDNN_ROOT_DIR:PATH" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8")

# KWIVER's vital.algo pybind11 wrappers are generated by parsing the headers
# with castxml, which uses its own bundled clang 13 and so cannot read the
# VS 2026 standard library at all. Have it emulate the VS 2019 toolset that is
# on this machine for CUDA instead -- it only reads declarations, the wrappers
# are still compiled by the VS 2026 compiler above.
set( VIAME_CASTXML_MSVC
  "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" )
if( EXISTS "${VIAME_CASTXML_MSVC}" )
  add_option("KWIVER_PYBIND11_CASTXML_COMPILER:FILEPATH" "${VIAME_CASTXML_MSVC}")
else()
  message( WARNING "No VS 2019 toolset for castxml; "
    "the KWIVER pybind11 wrapper generation will likely fail" )
endif()

# Windows-specific build paths
add_option("VIAME_BUILD_FLETCH_DIR" "C:/tmp/fl1")
add_option("VIAME_BUILD_KWIVER_DIR" "C:/tmp/kv1")
add_option("VIAME_BUILD_PLUGINS_DIR" "C:/tmp/vm1")

# Windows-specific overrides
add_option("VIAME_BUILD_DIVE_FROM_SOURCE" "ON")
add_option("VIAME_BUILD_MAX_THREADS" "5")

# SeaGIS plugin enable and dir
add_option("VIAME_ENABLE_SEAGIS" "ON")
add_option("SEAGIS_ROOT_DIR" "C:/Program Files/SeaGIS")

# Always enable the VIAME test suite so build_server_windows.bat can run
# the CRITICAL ctest set after build. Test sources are referenced via
# CMAKE_CURRENT_SOURCE_DIR and are not installed; the only side effect on
# the packaged zip is ~1.5 MB of pytest + deps under site-packages.
add_option("VIAME_ENABLE_TESTS:BOOL" "ON")

# Finalize OPTIONS variable
finalize_options()

set(platform Windows10)
