
function( FormatPassdowns _str _varResult )
  set( _tmpResult "" )
  get_cmake_property( _vars VARIABLES )
  string( REGEX MATCHALL "(^|;)${_str}[A-Za-z0-9_]*" _matchedVars "${_vars}" )
  foreach( _match ${_matchedVars} )
    set( _tmpResult ${_tmpResult} "-D${_match}=${${_match}}" )
  endforeach()
  set( ${_varResult} ${_tmpResult} PARENT_SCOPE )
endfunction()

function( DownloadFile URL OutputLoc MD5 )
  file( DOWNLOAD ${URL} ${OutputLoc} EXPECTED_MD5 ${MD5} )
endfunction()

function( RenameSubstr _dirName _inStr _outStr )
  file( GLOB DIR_FILES ${_dirName}/* )
  foreach( FN ${DIR_FILES} )
    get_filename_component( FN_WO_DIR ${FN} NAME )
    if( ${FN_WO_DIR} MATCHES "*${_inStr}*" )
	  get_filename_component( FN_DIR ${FN} DIRECTORY )
	  string( REPLACE "${_inStr}" "${_outStr}" NEW_FN ${FN_WO_DIR} )
	  file( RENAME "${FN}" "${FN_DIR}${FN_WO_DIR}" )
	endif()
  endforeach( loop_var )
endfunction()

function( CopyFiles _inRegex _outDir )
  file( GLOB FILES_TO_COPY ${_inRegex} )
  if( FILES_TO_COPY )
    file( COPY ${FILES_TO_COPY} DESTINATION ${_outDir} )
  endif()
endfunction()

function( RemoveDir _inDir )
  file( REMOVE_RECURSE ${_inDir} )
endfunction()