# Central location for KWIVER external dependency declaration and resolution

include( kwiver-depends-Boost )
include( kwiver-depends-Eigen )
include( kwiver-depends-CUDA )
include( kwiver-depends-OpenCV )
include( kwiver-depends-PROJ )
include( kwiver-depends-VisCL )
include( kwiver-depends-log4cxx )
include( kwiver-depends-log4cplus )
include( kwiver-depends-Ceres )
include( kwiver-depends-VXL )
include( kwiver-depends-Matlab )
include( kwiver-depends-TinyXML )
include( kwiver-depends-darknet )
include( kwiver-depends-Burn-Out )
