
# Pytorch depends on python
CMAKE_DEPENDENT_OPTION( KWIVER_ENABLE_PYTORCH
  "Enable pytorch arrow" OFF
  KWIVER_ENABLE_PYTHON OFF )

CMAKE_DEPENDENT_OPTION( KWIVER_ENABLE_PYTORCH_PYSOT
  "Enable pytorch pysot arrow" OFF
  KWIVER_ENABLE_PYTORCH OFF )
