###
# Static plugin registration
#
# `algorithms_create_plugin( lib register_algorithms.cxx )` used to build a
# MODULE library for the loader to `dlopen` at run time. P8-T03 replaces that:
# the registration file is compiled into the library itself and its entry
# point is called directly, so there is no module to find and no directory to
# search.
#
# The entry point is renamed **by the preprocessor** rather than in the
# source. Every registration file in the tree defines `register_factories`, so
# linking them together would collide; compiling with
# `-Dregister_factories=viame_register_<lib>` gives each a unique symbol and
# leaves every one of those files untouched.
#
# The list of registered libraries is collected in a global property and
# written out by `viame_write_static_registry`, which
# `library/algorithm_framework/registry` calls once every other subdirectory
# has been added.
##

define_property( GLOBAL PROPERTY viame_static_registrations
  BRIEF_DOCS "Libraries with a statically called registration function"
  FULL_DOCS  "Each entry is a library name whose registration file was "
             "compiled in by viame_register_statically." )

define_property( GLOBAL PROPERTY viame_static_registration_kinds
  BRIEF_DOCS "The plugin_type of each statically registered library"
  FULL_DOCS  "Parallel to viame_static_registrations: the plugin_type name "
             "that decides which load_all_plugins calls run it." )

###
# Record a registration file that is already part of its library.
#
#   viame_mark_static_registration( target kind source... )
#
# Renames the entry point and adds the target to the generated registry. Used
# by `viame_add_plugin`, whose sources are given to `viame_add_library`
# directly.
#
# `kind` is one of the `plugin_manager::plugin_type` names -- `APPLETS`,
# `PROCESSES`, `OTHERS` -- and is the directory the plugin used to be
# installed in, under a different name. It is what lets
# `load_all_plugins( APPLETS )` still cost nothing but the applets: the
# generated registry skips a library whose kind is not asked for, so
# dispatching `viame train` does not import every python plugin first.
##
function( viame_mark_static_registration target kind )
  # A library registered after the registry has been written is compiled,
  # linked, installed -- and never called, which looks exactly like an
  # algorithm that was never written. Say so instead.
  get_property( written GLOBAL PROPERTY viame_static_registry_written )
  if( written )
    message( FATAL_ERROR
      "${target} registers after the static registry was written; move its "
      "add_subdirectory above library/algorithm_framework/registry" )
  endif()

  set_source_files_properties( ${ARGN}
    TARGET_DIRECTORY ${target}
    PROPERTIES COMPILE_DEFINITIONS
      "register_factories=viame_register_${target}" )

  set_property( GLOBAL APPEND PROPERTY viame_static_registrations ${target} )
  set_property( GLOBAL APPEND PROPERTY viame_static_registration_kinds ${kind} )
endfunction()

###
# Compile a registration file into the library it registers.
#
#   viame_register_statically( base_lib source... )
#
# `base_lib` must already exist as a target.
##
function( viame_register_statically base_lib )
  if( NOT TARGET ${base_lib} )
    message( FATAL_ERROR
      "viame_register_statically: no such target ${base_lib}" )
  endif()

  # The registration sources reach for the export header of the MODULE that
  # used to carry them -- `<base_lib>_plugin_export.h`, holding
  # `<BASE_LIB>_PLUGIN_EXPORT`. That module is gone, so the header is written
  # here instead. It says the same thing: the entry point keeps default
  # visibility in a tree built with `-fvisibility=hidden`.
  string( TOUPPER "${base_lib}_plugin" macro_prefix )
  set( shim_dir "${CMAKE_CURRENT_BINARY_DIR}/static_registration" )
  set( shim "${shim_dir}/${base_lib}_plugin_export.h" )

  # `file( GENERATE )` rather than `file( WRITE )`: it leaves the file alone
  # when the content has not changed, so reconfiguring does not recompile
  # every registration file in the tree.
  file( GENERATE OUTPUT "${shim}" CONTENT
"/* Generated by viame_register_statically. The registration file for
 * ${base_lib} was compiled into the library rather than into a loadable
 * module, so the module's export header no longer exists; this stands in
 * for it. */

#ifndef ${macro_prefix}_EXPORT_H
#define ${macro_prefix}_EXPORT_H

#if defined( _WIN32 ) || defined( __CYGWIN__ )
#  define ${macro_prefix}_EXPORT __declspec( dllexport )
#else
#  define ${macro_prefix}_EXPORT __attribute__( ( visibility( \"default\" ) ) )
#endif

#define ${macro_prefix}_NO_EXPORT
#define ${macro_prefix}_DEPRECATED

#endif
" )

  target_include_directories( ${base_lib} PRIVATE "${shim_dir}" )
  target_sources( ${base_lib} PRIVATE ${ARGN} )

  # The registry calls it and the loader is its argument, so both come along.
  target_link_libraries( ${base_lib} PRIVATE kwiver::vital_vpm )

  # The algorithm plugins installed into the `modules` directory, which the
  # loader reads as `OTHERS`; the `algorithms` directory the `ALGORITHMS` bit
  # names has never existed in this tree.
  viame_mark_static_registration( ${base_lib} OTHERS ${ARGN} )
endfunction()

###
# Write the generated registry.
#
#   viame_write_static_registry( output_file )
#
# One declaration and one call per registered library, in the order the
# libraries were added -- which is the order CMake walked the tree, so a
# library is registered after the ones it was built on top of.
##
function( viame_write_static_registry output )
  get_property( libs  GLOBAL PROPERTY viame_static_registrations )
  get_property( kinds GLOBAL PROPERTY viame_static_registration_kinds )

  # The two properties are appended to together and read side by side.
  list( LENGTH libs  lib_count )
  list( LENGTH kinds kind_count )
  if( NOT lib_count EQUAL kind_count )
    message( FATAL_ERROR
      "static registration: ${lib_count} libraries but ${kind_count} kinds" )
  endif()

  set( declarations "" )
  set( calls "" )
  set( seen "" )
  set( index 0 )

  foreach( lib IN LISTS libs )
    list( GET kinds ${index} kind )
    math( EXPR index "${index} + 1" )

    if( lib IN_LIST seen )
      continue()
    endif()
    list( APPEND seen ${lib} )

    string( APPEND declarations
      "extern \"C\" void viame_register_${lib}( viame::registry& );\n" )
    string( APPEND calls
      "  if( types & pm::plugin_type::${kind} )\n"
      "  {\n"
      "    loader.set_registering_library( \"${lib}\" );\n"
      "    viame_register_${lib}( loader );\n"
      "  }\n" )
  endforeach()

  list( LENGTH seen count )

  configure_file(
    "${VIAME_SOURCE_DIR}/library/algorithm_framework/registry/static_registry.cxx.in"
    "${output}"
    @ONLY )

  set_property( GLOBAL PROPERTY viame_static_registry_written TRUE )

  message( STATUS "Static plugin registry: ${count} libraries" )
endfunction()
