#!/bin/bash

# Backwards compatibility wrapper: viame_resample_tracks -> viame resample-tracks
# This script will be removed once all tools are updated.
exec "$(dirname "$(readlink -f "$0")")/viame" resample-tracks "$@"
